# -*- coding: utf-8 -*-
"""Confusion_Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-z32AzvCEwFef2-xD6GpRFJC5l-Qqxl
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,r2_score,mean_squared_error
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("dil.csv")
df
x=df.drop('target',axis=1)
y=df['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of Logistic Model:",accuracy)
print("R2 Score:",r2_score(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))

scaler=StandardScaler()
x_train_sc=scaler.fit_transform(x_train)
x_test_sc=scaler.transform(x_test)
model=model.fit(x_train_sc,y_train)
y_pred=model.predict(x_test_sc)
print("ACCURACY AFTER SCALING",accuracy_score(y_test,y_pred))
print("R2 Score after scaling:",r2_score(y_test,y_pred))
print("MSE after scaling:",mean_squared_error(y_test,y_pred))

