# -*- coding: utf-8 -*-
"""Cross_Validation_Model_Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0sx8UK6NrFU0czW1UKDj0gmQs3aEs4c
"""

import pandas as pd

df=pd.read_csv('dil.csv')
df
X=df.drop('target',axis=1)
y=df['target']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

lr=LogisticRegression()
lr_scores=cross_val_score(lr,X_scaled,y,cv=5)

dt=DecisionTreeClassifier()
dt_scores=cross_val_score(dt,X,y,cv=5)

rf=RandomForestClassifier()
rf_scores=cross_val_score(rf,X,y,cv=5)

svm=SVC()
SVM=cross_val_score(svm,X_scaled,y,cv=5)

knn=KNeighborsClassifier()
knn_scores=cross_val_score(knn,X_scaled,y,cv=5)

results=pd.DataFrame({'model':["lgogistic regression",
                               "decision tree",
                               "random forest",
                               "support vector machine",
                               "knn"],
                      "score":[
                                lr_scores.mean(),
                                dt_scores.mean(),
                                rf_scores.mean(),
                                SVM.mean(),
                                knn_scores.mean()
                      ]
                      })
print(results)

# SO WE SHOUL PICH THE RANDOM FOREST MODEL BECAUSE ITS SCORE
#  OF ACCURACY IS THE HIGHES THEREFORE DECISION TREE HAS ALSO
# SAME ACCURACY SCORE BUT IN DECISION TREE MODEL THGERE IS A
# LOT CHANCES OF OVERFITTING SO RANDOM FPREST I BEST FOR IT



