# -*- coding: utf-8 -*-
"""Customer_Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X82gMCNZsCgAHxjfmLlQSpjZasbIXj9G
"""

# <CUSTOMER CHURN PREDICTION USING MACHINE LEARNING>

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df=pd.read_csv('customer_churn.csv')
df

df.head()
df.columns

# ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
#        'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
#        'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
#        'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
#        'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

# Data columns :------
#  #   Column            Non-Null Count  Dtype
# ---  ------            --------------  -----
#  0   customerID        7043 non-null   object
#  1   gender            7043 non-null   object
#  2   SeniorCitizen     7043 non-null   int64
#  3   Partner           7043 non-null   object
#  4   Dependents        7043 non-null   object
#  5   tenure            7043 non-null   int64
#  6   PhoneService      7043 non-null   object
#  7   MultipleLines     7043 non-null   object
#  8   InternetService   7043 non-null   object
#  9   OnlineSecurity    7043 non-null   object
#  10  OnlineBackup      7043 non-null   object
#  11  DeviceProtection  7043 non-null   object
#  12  TechSupport       7043 non-null   object
#  13  StreamingTV       7043 non-null   object
#  14  StreamingMovies   7043 non-null   object
#  15  Contract          7043 non-null   object
#  16  PaperlessBilling  7043 non-null   object
#  17  PaymentMethod     7043 non-null   object
#  18  MonthlyCharges    7043 non-null   float64
#  19  TotalCharges      7043 non-null   object
#  20  Churn             7043 non-null   object

df.head()
df.columns
df.dtypes
df.shape
df.info()
df.isnull().sum()
df.duplicated().sum()
df.describe()
df['Churn'].value_counts()
df.head()

sns.countplot(x='Churn',data=df)
plt.show()

sns.countplot(x='gender',hue='Churn',data=df)
plt.show()

sns.countplot(x='Contract',hue='Churn',data=df)

plt.show()

sns.histplot(df['MonthlyCharges'],kde=True)
plt.show()

df.drop("customerID",axis=1,inplace=True)

le=LabelEncoder()
for col in df.columns:
  if df[col].dtype=='Object':
    df[col]=le.fit_transform(df[col])

x=df.drop("Churn",axis=1)
y=df['Churn']

df.info()
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
df['TotalCharges'].dtype
df.info()
df.isnull().sum()
df['TotalCharges'].fillna(
    df['TotalCharges'].median(),
    inplace=True
)
df['Churn']=df['Churn'].map({'yes':1,'no':0})

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in x.columns:
    if x[col].dtype == 'object':
        x[col] = le.fit_transform(x[col])

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression()
lr_model.fit(X_train_scaled,y_train)
y_pred=lr_model.predict(X_test_scaled)
lr_acc=accuracy_score(y_test,y_pred)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

print(lr_model.score(X_train_scaled,y_train))
print(lr_model.score(X_test_scaled,y_test))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm,
            annot=True,
            fmt='d')
plt.show()
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

knn_acc=accuracy_score(y_test, y_pred_knn)
print(knn.score(X_train_scaled,y_train))
print(knn.score(X_test_scaled,y_test))

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(x_train, y_train)

y_pred_dt = dt.predict(x_test)

dt_acc=accuracy_score(y_test, y_pred_dt)
print(knn.score(x_train,y_train))
print(knn.score(x_test,y_test))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)

rf_Acc=accuracy_score(y_test, y_pred_rf)
print(rf.score(x_train,y_train))
print(rf.score(x_test,y_test))

from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train_scaled,y_train)
y_pred_svm = svm.predict(X_test_scaled)
svm_acc=accuracy_score(y_test,y_pred_svm)
print(svm.score(X_train_scaled,y_train))
print(svm.score(X_test_scaled,y_test))

from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()
nb.fit(X_train_scaled,y_train)
y_pred_nb=nb.predict(X_test_scaled)
nb_acc=accuracy_score(y_test,y_pred_nb)
print(nb.score(X_train_scaled,y_train))
print(nb.score(X_test_scaled,y_test))

from sklearn.ensemble import GradientBoostingClassifier

gb=GradientBoostingClassifier()

gb.fit(x_train, y_train)

y_pred_gb = gb.predict(x_test)

gb_acc = accuracy_score(y_test, y_pred_gb)

print("Gradient Boosting Accuracy:", gb_acc)
print(gb.score(x_train,y_train))
print(gb.score(x_test,y_test))

result=pd.DataFrame({
    'model':[
        'LogisticRegression',
        'KNeighborsClassifier',
        'DecisionTreeClassifier',
        'RandomForestClassifier',
        'SVC',
        'GaussianNB',
        'GradientBoostingClassifier'
    ],
    'accuracy':[
           lr_acc,
           knn_acc,
           dt_acc,
           rf_Acc,
           svm_acc,
           nb_acc,
           gb_acc
    ]
})
result.sort_values(by='accuracy',ascending=False)

sns.barplot(data=result,x='model',y='accuracy')
plt.xticks(rotation=90)
plt.show()

importance = pd.DataFrame({
    'Feature':x.columns,
    'Importance':rf.feature_importances_
})

importance.sort_values(
    by='Importance',
    ascending=False,
    inplace=True
)

sns.barplot(data=importance.head(10),x='Importance',y='Feature')
plt.show()

from sklearn.model_selection import cross_val_score
scores=cross_val_score(rf,x,y,cv=5)
print(scores)

print(scores.mean())

# lr_scores=cross_val_score(lr_model,x,y,cv=5)
# print(lr_scores)
# print(lr_scores.mean())

#hyperparameter tuning
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators':[10,20,50,80,100,150,200],
    'max_depth':[2,5,7,10,12,15,17]
}

grid=GridSearchCV(rf,params,cv=5)
grid.fit(x_train,y_train)
print(grid.best_params_)
print(grid.best_score_)

best_rf=grid.best_estimator_
pred=best_rf.predict(x_test)
print(accuracy_score(y_test,pred))

import joblib

joblib.dump(
    best_rf,
    "customer_churn_model.pkl"
)

df.head()

