# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upXkRNedfxs-_RjB0euZj07C6kDLXt8k
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

df=pd.read_csv("dil.csv")
df

x=df.drop("target",axis=1)
y=df['target']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

for depth in range(1,11):
  model=DecisionTreeClassifier(max_depth=depth,criterion='entropy',random_state=42)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  accuracy=accuracy_score(y_test,y_pred)
  print(f"accuracyis {accuracy:.4f}")

  from sklearn.tree import plot_tree
  plt.figure(figsize=(10,8))
  plot_tree(model, feature_names=x.columns, class_names=["no disease", "disease"], filled=True)

