# -*- coding: utf-8 -*-
"""FeatureScaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10NOr87LIQFYQFUKuVfdxWO-PJKPcTAr7
"""

import pandas as pd

df1 = pd.DataFrame({

    'Age':[18,22,25,27,30,35,40,45,50,55,
           60,62,65,27,29,31,33,37,39,41],

    'Salary':[1000,1500,2000,2200,2500,
              2700,3000,3200,3500,3700,
              1000000,1100000,1200000,
              4000,4200,4500,4700,5000,5200,5500],

    'Bought':[0,0,0,0,0,0,0,0,0,0,
              1,1,1,1,1,1,1,1,1,1]

})

print(df1)
x=df1[['Age','Salary']]
y=df1['Bought']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LogisticRegression()
model.fit(x_train,y_train)

print("Without Scaling R2:",model.score(x_test,y_test))

#Applying standarization
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
x_train_scalar=scalar.fit_transform(x_train)
x_test_scalar=scalar.transform(x_test)

model.fit(x_train_scalar,y_train)
print("With Scaling R2:",
      model.score(x_test_scalar, y_test))

#Applying normalization
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train_norm=scalar.fit_transform(x_train)
x_test_norm=scalar.transform(x_test)

model=LogisticRegression()
model.fit(x_train_norm,y_train)
s=model.score(x_test_norm,y_test)
print("r2_scorw with normalization",s)