# -*- coding: utf-8 -*-
"""HyperParameter_Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QiVe2nI5RrllJcrSSdUsTYL-r7Hx8FUM
"""

from sklearn.model_selection import GridSearchCV
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

df=pd.read_csv('dil.csv')
x=df.drop('target',axis=1)
y=df['target']

pg = {
    'n_estimators': [5,10,15,20,25,30,35,40,45,50,100,200],
    }
grid=GridSearchCV(RandomForestClassifier(random_state=42),param_grid=pg,cv=5,scoring='accuracy')

grid.fit(x,y)

print(grid.best_params_)

print(grid.best_score_)

