# -*- coding: utf-8 -*-
"""k_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YiDD9vr3TskLhzcHTF0LqlPdOhGPVLq
"""

import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

x=np.array([
    [20,30],
    [25,35],
    [30,40],
    [60,70],
    [65,75],
    [70,80]
])

model=KMeans(n_clusters=2)

model.fit(x)

labels=model.labels_

centroids=model.cluster_centers_

print("cluster label",labels)
print("centroids",centroids)

plt.scatter(x[:,0],x[:,1],c=labels,cmap='viridis')

plt.scatter(centroids[:,0],centroids[:,1],color='red',marker='x')
plt.xlabel("income")
plt.ylabel("spending")

