# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Otcc1Fd5dTv2NhjsVZEsRfVbJI5tkLJL
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

data = {
    'Height': [5.2, 5.5, 6.0, 6.2],
    'Weight': [50, 55, 80, 85],
    'Type': ['Weak', 'Weak', 'Strong', 'Strong']
}

df = pd.DataFrame(data)

print(df)

x=df[['Height','Weight']]
y=df['Type']

X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
pred=knn.predict(X_test)
acc=accuracy_score(y_test,pred)
print(acc)

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
df=pd.read_csv("dil.csv")
# print(df)
x=df.drop("target",axis=1)
y=df['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_scaled,y_train)
y_pred=knn.predict(x_test_scaled)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
y_pred

for k in range(1,11):
  knn=KNeighborsClassifier(n_neighbors=k)
  scaler=StandardScaler()
  x_train_sc=scaler.fit_transform(x_train)
  x_test_sc=scaler.transform(x_test)
  knn.fit(x_train_sc,y_train)
  y_pred=knn.predict(x_test_sc)
  accuracy=accuracy_score(y_test,y_pred)
  print(f"Accuracy for k={k}: {accuracy:.5f}")

