# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ww-AKVMJ1cdQi_KX-X0aQ2DhvJDHzTWF
"""

import pandas as pd

data = {
    "hours": [1,2,3,4,5,6,7,8],
    "attendance": [50,60,65,70,75,80,85,90],
    "pass": [0,0,0,1,1,1,1,1]   # 0 = fail, 1 = pass
}

df = pd.DataFrame(data)

x=df[['hours','attendance']]
y=df['pass']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit(x,y)
y_pred=model.predict(x_test)


from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(y_test,y_pred))

print(model.predict([[5,40]]))

