# -*- coding: utf-8 -*-
"""MachineLearning_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmU-ZKIVilkI4p9wepGlbD4zB-kw5MdI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

df=pd.read_csv('hkhk.csv')
df

x=df.drop('Y house price of unit area',axis=1)
y=df['Y house price of unit area']

x_train,x_test ,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LinearRegression()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

y_pred

mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print("mse",mse)
print("r2",r2)

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

data = {
    "hours": [1,2,3,4,5,6,7,8],
    "marks": [15,30,40,55,65,75,85,95]
}
df1 = pd.DataFrame(data)

x=df1[['hours']]
y=df1['marks']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
y_pred

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = {
    "area": [500, 800, 1000, 1200, 1500],
    "rooms": [1, 2, 2, 3, 3],
    "price": [50, 80, 100, 130, 150]
}

df = pd.DataFrame(data)

X = df[['area','rooms']]
y = df['price']
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("R2:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

plt.figure()
plt.scatter(df['area'], df['price'])
sorted_df = df.sort_values('area')
pred_line = model.predict(sorted_df[['area','rooms']])
plt.plot(sorted_df['area'], pred_line)
plt.xlabel("Area (sq ft)")
plt.ylabel("Price")
plt.title("House Price Prediction (Linear Regression)")

