# -*- coding: utf-8 -*-
"""MachineLearning_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M73xwGmamMTVejbmfiDXsUy0lfvn9SAF
"""

import numpy as np
from sklearn.linear_model import LinearRegression

hours=np.array([2,3,4,5,6,7])
marks=np.array([20,30,40,58,60,70])

x=hours.reshape(-1,1)
y=marks

model=LinearRegression()

model.fit(x,y)

y_predictions=model.predict(x)

print(model.predict([[9]]))

print("intercept",model.intercept_)

print("slope",model.coef_)

import matplotlib.pyplot as plt

plt.plot(x,y,marker='o')
plt.plot(x,y_predictions)
plt.xlabel("Hours")
plt.ylabel("Marks")
plt.show()

