# -*- coding: utf-8 -*-
"""ML_Preview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lbQYYFiT9lnrJpDevJf0xQRCFMjCcsR
"""

import pandas as pd
df=pd.read_csv("realestate.csv")
df

x=df.drop("Y house price of unit area",axis=1)#features
y=df["Y house price of unit area"]#target

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(y_pred)
df

from sklearn.metrics import mean_squared_error,r2_score
mse=mean_squared_error(y_test,y_pred)

# r2_score=r2_score(y_test,y_pred)
print(mse)
print(r2_score)

#overfitting check
train_pred=model.predict(x_train)
test_pred=model.predict(x_test)


# print("train r2_score is:",r2_score(y_train,train_pred))

# print("test r2_score is:",r2_score(y_test,test_pred))

df

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import pandas as pd
df=pd.read_csv("realestate.csv")
df

x=df.drop("Y house price of unit area",axis=1)#features
y=df["Y house price of unit area"]#target
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_poly,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)

# mse=mean_squared_error(y_test,y_pred)
# r_2=r2_score(y_test,y_pred)
# print("mean square error",mse)
# print("r2_score",r_2)

import pandas as pd

df1 = pd.DataFrame({

    'Age':[18,22,25,27,30,35,40,45,50,55,
           60,62,65,27,29,31,33,37,39,41],

    'Salary':[1000,1500,2000,2200,2500,
              2700,3000,3200,3500,3700,
              1000000,1100000,1200000,
              4000,4200,4500,4700,5000,5200,5500],

    'Bought':[0,0,0,0,0,0,0,0,0,0,
              1,1,1,1,1,1,1,1,1,1]

})

print(df1)
x=df1[['Age','Salary']]
y=df1['Bought']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LogisticRegression()
model.fit(x_train,y_train)

print("Without Scaling R2:",model.score(x_test,y_test))

#Applying standarization
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
x_train_scalar=scalar.fit_transform(x_train)
x_test_scalar=scalar.transform(x_test)

model.fit(x_train_scalar,y_train)
print("With Scaling R2:",
      model.score(x_test_scalar, y_test))

#Applying normalization
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train_norm=scalar.fit_transform(x_train)
x_test_norm=scalar.transform(x_test)

model=LogisticRegression()
model.fit(x_train_norm,y_train)
s=model.score(x_test_norm,y_test)
print("r2_scorw with normalization",s)

