# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Twb_8ZTBuxi1GCslYWB6Voq9BjML0VAI
"""

import pandas as pd
from sklearn.model_selection import train_test_split

# Load the dataset
df = pd.read_csv('dil.csv')

x=df.drop('target',axis=1)
y=df['target']

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_test shape: {y_test.shape}")

import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100,max_depth=5,random_state=42)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy}")

importance=rf.feature_importances_
features=x.columns

plt.figure(figsize=(10,5))
plt.bar(features,importance)
plt.xticks(rotation=45)
plt.title('Feature Importance')
plt.show()

from sklearn.tree import plot_tree
plt.figure(figsize=(15,10))
plot_tree(rf.estimators_[49],filled=True,feature_names=x.columns,class_names=['no disease','disease'],rounded=True)
plt.show()

