# -*- coding: utf-8 -*-
"""Regularization_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVqIXL0kOByqewLZpmmj79rk_rX_JK9a
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

df=pd.read_csv("realestate.csv")
df
x=df.drop("Y house price of unit area",axis=1)
y=df['Y house price of unit area']

if 'No'in x.columns:
  x=x.drop('No',axis=1)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)

#regularization=lasso/lasso + regression
#Ridge regression
ridge_model_sclaed=Ridge(alpha=1.0)
ridge_model_sclaed.fit(x_train_scale,y_train)

y_pred_lasso=ridge_model_sclaed.predict(x_test_scale)

print("r2 score of ridge is:",r2_score(y_test,y_pred_lasso))
print("mean squared error of ridge is",mean_squared_error(y_test,y_pred_lasso))

#Lasso regression
lasso_model=Lasso(alpha=1.0)
lasso_model.fit(x_train_scale,y_train)
y_pred=lasso_model.predict(x_test_scale)

print("r2 score of lasso is:",r2_score(y_test,y_pred))
print("mean squared error of lasso is",mean_squared_error(y_test,y_pred))

